"""
API 응답 컬럼명 → 한국어 매핑 상수
"""

MAPPING_KOR_COLUMNS = {
    # ── 계좌잔고 output1 (보유종목) ──
    "pdno": "종목코드",
    "prdt_name": "종목명",
    "trad_dvsn_name": "매매구분명",
    "bfdy_buy_qty": "전일매수수량",
    "bfdy_sll_qty": "전일매도수량",
    "thdt_buyqty": "금일매수수량",
    "thdt_sll_qty": "금일매도수량",
    "hldg_qty": "보유수량",
    "ord_psbl_qty": "주문가능수량",
    "pchs_avg_pric": "매입평균가격",
    "pchs_amt": "매입금액",
    "prpr": "현재가",
    "evlu_amt": "평가금액",
    "evlu_pfls_amt": "평가손익금액",
    "evlu_pfls_rt": "평가손익율",
    "evlu_erng_rt": "평가수익율",
    "loan_dt": "대출일자",
    "loan_amt": "대출금액",
    "stln_slng_chgs": "대주매각대금",
    "expd_dt": "만기일자",
    "fltt_rt": "등락율",
    "bfdy_cprs_icdc": "전일대비증감",
    "item_mgna_rt_name": "종목증거금율명",
    "grta_rt_name": "보증금율명",
    "sbst_pric": "대용가격",
    "stck_loan_unpr": "주식대출단가",

    # ── 계좌잔고 output2 (계좌 요약) ──
    "dnca_tot_amt": "예수금총금액",
    "nxdy_excc_amt": "익일정산금액",
    "prvs_rcdl_excc_amt": "가수도정산금액",
    "cma_evlu_amt": "CMA평가금액",
    "bfdy_buy_amt": "전일매수금액",
    "thdt_buy_amt": "금일매수금액",
    "nxdy_auto_rdpt_amt": "익일자동상환금액",
    "bfdy_sll_amt": "전일매도금액",
    "thdt_sll_amt": "금일매도금액",
    "d2_auto_rdpt_amt": "D+2자동상환금액",
    "bfdy_tlex_amt": "전일제비용금액",
    "thdt_tlex_amt": "금일제비용금액",
    "tot_loan_amt": "총대출금액",
    "scts_evlu_amt": "유가평가금액",
    "tot_evlu_amt": "총평가금액",
    "nass_amt": "순자산금액",
    "fncg_gld_auto_rdpt_yn": "융자금자동상환여부",
    "pchs_amt_smtl_amt": "매입금액합계금액",
    "evlu_amt_smtl_amt": "평가금액합계금액",
    "evlu_pfls_smtl_amt": "평가손익합계금액",
    "tot_stln_slng_chgs": "총대주매각대금",
    "bfdy_tot_asst_evlu_amt": "전일총자산평가금액",
    "asst_icdc_amt": "자산증감액",
    "asst_icdc_erng_rt": "자산증감수익율",

    # ── 주문체결 output1 (체결내역) ──
    "odno": "주문번호",
    "orgn_odno": "원주문번호",
    "ord_dt": "주문일자",
    "ord_tmd": "주문시각",
    "ord_gno_brno": "주문점번호",
    "sll_buy_dvsn_cd": "매도매수구분",
    "sll_buy_dvsn_cd_name": "매도매수구분명",
    "ord_qty": "주문수량",
    "ord_unpr": "주문단가",
    "tot_ccld_qty": "총체결수량",
    "tot_ccld_amt": "총체결금액",
    "avg_prvs": "평균단가",
    "ccld_cndi_name": "체결조건명",
    "ord_dvsn_name": "주문구분명",
    "rmn_qty": "잔여수량",
    "ccld_qty": "체결수량",
    "ccld_unpr": "체결단가",
    "inqr_dvsn_name": "조회구분명",
    "infm_tmd": "통보시각",
    "ctac_tlno": "연락전화번호",
    "prdt_type_cd": "상품유형코드",
    "excg_dvsn_cd": "거래소구분코드",
    "cpbc_ordp_mtrl_dvsn_cd": "주문매체구분코드",
    "ord_orgno": "주문기관번호",
    "rsvn_ord_end_dt": "예약주문종료일",
    "excg_id_dvsn_cd": "거래소ID구분코드",
    "stpm_cndt_pric": "스탑조건가격",
    "stpm_efct_occr_dtmd": "스탑효력발생일시",

    # ── 주문체결 output2 (요약) ──
    "tot_ord_qty": "총주문수량",
    "prsm_tlex_smtl": "추정제비용합계",
}
